In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame

* Load the csv exported in Part I to a DataFrame

In [2]:
# Reference the file where the CSV is located
cities_csv_path = "../WeatherPy/cities.csv"

# Import the data into a Pandas DataFrame
cities_df = pd.read_csv(cities_csv_path, index_col='Unnamed: 0')
cities_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Akdepe,42.0551,59.3788,37.40,65,0,11.50,TM,1612975048
1,Sept-Îles,50.2001,-66.3821,12.99,44,20,13.80,CA,1612974842
2,Atuona,-9.8000,-139.0333,78.93,77,6,20.31,PF,1612975051
3,Maragogi,-9.0122,-35.2225,83.86,69,74,13.38,BR,1612975052
4,Monastyrshchina,54.3496,31.8380,0.91,93,92,7.25,RU,1612975053
...,...,...,...,...,...,...,...,...,...
559,Saint-Anselme,46.6292,-70.9734,19.00,95,100,8.05,CA,1612975698
560,San Rafael,-34.6177,-68.3301,74.25,48,48,7.27,AR,1612975699
561,Grand-Santi,4.2500,-54.3833,88.16,49,100,4.56,GF,1612975701
562,Port Montt,-41.4698,-72.9447,80.60,54,0,4.61,CL,1612975702
563,‘Ewa Beach,21.3156,-158.0072,60.80,77,1,3.44,US,1612975703

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)

# Store 'Lat' and 'Lng' into locations
locations = cities_df[["Lat", "Lng"]].astype(float)

# Store 'Humidity' as list
humidity = cities_df["Humidity"].astype(float)

In [4]:
# Create humidity heatmap
fig = gmaps.figure(zoom_level=2, center=(16.276737, 1.482970))

heat_layer = gmaps.heatmap_layer(locations, weights=humidity,
                                 dissipating=False, max_intensity=100,
                                 point_radius=4)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
# Drop cities with max temperature 80 degrees or higher
new_df = cities_df.loc[(cities_df["Max Temp"] < 80)]

# Drop cities with max teperature lower than 70 degrees
new_df = new_df.loc[(new_df["Max Temp"] > 70)]

# Drop cities with wind speed 10 mph or greater
new_df = new_df.loc[(new_df["Wind Speed"] < 10)]

# Drop cities with cloudiness greater than 0
new_df = new_df.loc[(new_df["Cloudiness"] == 0)]
new_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
6,Hermanus,-34.4187,19.2345,79.00,63,0,8.01,ZA,1612975055
143,Marrakesh,31.6315,-8.0083,73.40,43,0,3.44,MA,1612975213
319,Santa Vitória do Palmar,-33.5189,-53.3681,77.47,70,0,9.82,BR,1612975322
374,Sompeta,18.9333,84.6000,70.16,66,0,5.10,IN,1612975483
397,Kovvūr,17.0167,81.7333,75.20,78,0,5.75,IN,1612975511
441,Deniliquin,-35.5333,144.9667,73.99,50,0,7.09,AU,1612975562
507,Salalah,17.0151,54.0924,77.00,44,0,2.30,OM,1612975638

### Hotel Map
* Store into variable named `hotel_df`.
* Add a \"Hotel Name\" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
# Store DataFrame into new variable called 'hotel_df'
hotel_df = new_df

# Add "Hotel Name" column to the DataFrame
hotel_df["Hotel Name"] = ""
hotel_df

# Set parameters to search for hotels within 5000 meters
params = {
    "radius": 5000,
    "types": "lodging",
    "key": g_key
}

# Use for loop to locate the first hotel
for index, row in hotel_df.iterrows():
    
    # Get Lat & Lng from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Change location each iteration while leaving origional params in place
    params["location"] = f"{lat},{lng}"
    
    # Set base URL
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # Make request and print URL
    hotel_name = requests.get(base_url, params=params)
    
    # Convert to json
    hotel_name = hotel_name.json()
    
    # In case there may be missing data, use try-except to skip any missing data
    try:
        hotel_df.loc[index, "Hotel Name"] = hotel_name["results"][0]["name"]
    except:
        print("Missin field/result ... skipping")

In [8]:
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
6,Hermanus,-34.4187,19.2345,79.00,63,0,8.01,ZA,1612975055,Misty Waves Boutique Hotel
143,Marrakesh,31.6315,-8.0083,73.40,43,0,3.44,MA,1612975213,Les Jardins de La Koutoubia
319,Santa Vitória do Palmar,-33.5189,-53.3681,77.47,70,0,9.82,BR,1612975322,Hostel Comodoro
374,Sompeta,18.9333,84.6000,70.16,66,0,5.10,IN,1612975483,బెంకిలి భైరొడమ్మ క్రికెట్ గ్రౌండ్
397,Kovvūr,17.0167,81.7333,75.20,78,0,5.75,IN,1612975511,Hotel Rathna Palace
441,Deniliquin,-35.5333,144.9667,73.99,50,0,7.09,AU,1612975562,Riviana Motel
507,Salalah,17.0151,54.0924,77.00,44,0,2.30,OM,1612975638,HAMDAN PLAZA HOTEL SALALAH

In [9]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [17]:
# Add marker layer ontop of heat map
marker_layer = gmaps.marker_layer(locations, info_box_content= hotel_info)

# Display figure
# Create combined map
fig = gmaps.figure(zoom_level=2, center=(16.276737, 1.482970))
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

fig

Figure(layout=FigureLayout(height='420px'))